"use client";

import React, { useState } from "react";
import { StartupPlan } from "@/types/startup";
import {
  FileDown,
  Printer,
  Code2,
  FileText,
  Check,
  Package,
} from "lucide-react";

interface ExportBarProps {
  plan: StartupPlan;
}

export const ExportBar: React.FC<ExportBarProps> = ({ plan }) => {
  const [copiedStatus, setCopiedStatus] = useState<string | null>(null);

  const handlePrintPdf = () => {
    window.print();
  };

  const handleExportMarkdown = () => {
    const md = `# Startup Blueprint: ${plan.idea}
Generated by PitchPilot in ${plan.durationSeconds}s

## 1. Executive Summary & Problem
- **Target Market**: ${plan.research.targetMarket}
- **Problem Statement**: ${plan.strategy.problemStatement}
- **Why Now**: ${plan.strategy.whyNow}
- **Single Biggest Opportunity**: ${plan.strategy.singleBiggestOpportunity}
- **Unfair Advantage**: ${plan.strategy.unfairAdvantage}

## 2. Market Sizing (TAM / SAM / SOM)
- **TAM**: ${plan.research.marketSize.tam.value} - ${plan.research.marketSize.tam.description}
- **SAM**: ${plan.research.marketSize.sam.value} - ${plan.research.marketSize.sam.description}
- **SOM**: ${plan.research.marketSize.som.value} - ${plan.research.marketSize.som.description}

## 3. Direct Competitors
${plan.research.competitors
  .map(
    (c) => `- **${c.name}** (${c.threatLevel} Threat): ${c.oneLineDifferentiation} [Weakness: ${c.weakness}]`
  )
  .join("\n")}

## 4. MVP Feature Roadmap
### Must-Have (P0):
${plan.spec.mustHave.map((f) => `- **${f.name}**: ${f.techApproach}`).join("\n")}

### Should-Have (P1):
${plan.spec.shouldHave.map((f) => `- **${f.name}**: ${f.techApproach}`).join("\n")}

### Could-Have (P2):
${plan.spec.couldHave.map((f) => `- **${f.name}**: ${f.techApproach}`).join("\n")}
`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `startup-blueprint-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
    setCopiedStatus("md");
    setTimeout(() => setCopiedStatus(null), 2000);
  };

  const handleExportJson = () => {
    const blob = new Blob([JSON.stringify(plan, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `pitchpilot-bundle-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setCopiedStatus("json");
    setTimeout(() => setCopiedStatus(null), 2000);
  };

  return (
    <div className="sticky bottom-0 z-40 w-full border-t border-zinc-800 bg-[#0a0a0a]/95 backdrop-blur-md px-4 py-3 no-print">
      <div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <div className="flex h-2 w-2 rounded-full bg-emerald-400" />
          <span className="text-xs font-mono text-zinc-300">
            Startup Package Ready
          </span>
          <span className="text-[10px] text-zinc-500 font-mono hidden sm:inline">
            • {plan.durationSeconds}s generation
          </span>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {/* Print / Save Deck as PDF */}
          <button
            onClick={handlePrintPdf}
            className="flex items-center gap-1.5 rounded-md border border-zinc-800 bg-zinc-900 px-3 py-1.5 text-xs font-medium text-zinc-200 transition-colors hover:border-zinc-700 hover:text-white"
          >
            <Printer className="h-3.5 w-3.5 text-zinc-400" />
            <span>Download Deck (PDF)</span>
          </button>

          {/* Export Spec Markdown */}
          <button
            onClick={handleExportMarkdown}
            className="flex items-center gap-1.5 rounded-md border border-zinc-800 bg-zinc-900 px-3 py-1.5 text-xs font-medium text-zinc-200 transition-colors hover:border-zinc-700 hover:text-white"
          >
            {copiedStatus === "md" ? (
              <>
                <Check className="h-3.5 w-3.5 text-emerald-400" />
                <span className="text-emerald-400">Exported MD!</span>
              </>
            ) : (
              <>
                <FileText className="h-3.5 w-3.5 text-zinc-400" />
                <span>Export Spec (Markdown)</span>
              </>
            )}
          </button>

          {/* Export Full Bundle as JSON */}
          <button
            onClick={handleExportJson}
            className="flex items-center gap-1.5 rounded-md bg-white px-3 py-1.5 text-xs font-semibold text-black transition-colors hover:bg-zinc-200 shadow-sm"
          >
            {copiedStatus === "json" ? (
              <>
                <Check className="h-3.5 w-3.5 text-emerald-600" />
                <span>Saved JSON!</span>
              </>
            ) : (
              <>
                <Package className="h-3.5 w-3.5 text-black" />
                <span>Export Full Bundle (JSON)</span>
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
};
